# SPDX-FileCopyrightText: 2025 Lukas Winkler
#
# SPDX-License-Identifier: AGPL-3.0-or-later

server:
  host: localhost
  port: 8943
  data_attribution_link: "https://about.route.lw1.at"


osm: datasets/austria-latest.osm.pbf
tiles:
  profile: custom-tile-profile.lua
  db_size: 274877906944
  flush_threshold: 100000
timetable:
  first_day: -30
  num_days: 395
  tb: false
  railviz: true
  with_shapes: true
  adjust_footpaths: true
  merge_dupes_intra_src: false
  merge_dupes_inter_src: false
  link_stop_distance: 200
  update_interval: 60
  http_timeout: 30
  incremental_rt_update: false
  use_osm_stop_coordinates: false
  extend_missing_footpaths: false
  max_footpath_length: 25
  max_matching_distance: 25.000000
  preprocess_max_matching_distance: 0.000000
  datasets:
    00-eisenbahn:
      path: datasets/gtfs/00_eisenbahn.zip
      default_bikes_allowed: false
      default_cars_allowed: false
      extend_calendar: false
      script: scripts/colors.lua
    ferries:
      path: own_gtfs/gtfs_output/donau_f√§hren.zip
      default_bikes_allowed: false
      default_cars_allowed: false
      extend_calendar: false
    01-linz:
      path: datasets/gtfs/01_linz.zip
      default_bikes_allowed: false
      default_cars_allowed: false
      extend_calendar: false
      script: scripts/colors.lua
    02-ooe:
      path: datasets/gtfs/02_ooe.zip
      default_bikes_allowed: false
      default_cars_allowed: false
      extend_calendar: false
      script: scripts/colors.lua
    03-salzburg:
      path: datasets/gtfs/03_salzburg.zip
      default_bikes_allowed: false
      default_cars_allowed: false
      extend_calendar: false
      script: scripts/colors.lua
    04-kaernten:
      path: datasets/gtfs/04_kaernten.zip
      default_bikes_allowed: false
      default_cars_allowed: false
      extend_calendar: false
      script: scripts/colors.lua
      default_timezone: Europe/Vienna
    05-vor:
      path: datasets/gtfs/05_vor.zip
      default_bikes_allowed: false
      default_cars_allowed: false
      extend_calendar: false
      script: scripts/colors.lua
      rt:
        - url: https://unofficial-gtfsrt-proxy.route.lw1.at/vienna-gtfs-rt.pb
    06-steiermark:
      path: datasets/gtfs/06_steiermark.zip
      default_bikes_allowed: false
      default_cars_allowed: false
      extend_calendar: false
      script: scripts/colors.lua
    07-tirol:
      path: datasets/gtfs/07_tirol.zip
      default_bikes_allowed: false
      default_cars_allowed: false
      extend_calendar: false
      script: scripts/colors.lua
    08-vorarlberg:
      path: datasets/gtfs/08_vorarlberg.zip
      default_bikes_allowed: false
      default_cars_allowed: false
      extend_calendar: false
      script: scripts/colors.lua
    flixbus-gtfs-generic-eu:
      path: datasets/flixbus_gtfs_generic_eu.zip
      default_bikes_allowed: false
      default_cars_allowed: false
      extend_calendar: false
      script: scripts/eu-flixbus.lua

elevators: false
osr_footpath: true
geocoding: true
reverse_geocoding: true

street_routing:
  elevation_data_dir: ./datasets/hgt
