server:
  host: localhost
  port: 8943


osm: datasets/austria-latest.osm.pbf
tiles:
  profile: tiles-profiles/full.lua
  db_size: 274877906944
  flush_threshold: 100000
timetable:
  first_day: TODAY
  num_days: 365
  tb: false
  railviz: true
  with_shapes: true
  adjust_footpaths: true
  merge_dupes_intra_src: false
  merge_dupes_inter_src: false
  link_stop_distance: 200
  update_interval: 60
  http_timeout: 30
  incremental_rt_update: false
  use_osm_stop_coordinates: false
  extend_missing_footpaths: false
  max_footpath_length: 25
  max_matching_distance: 25.000000
  preprocess_max_matching_distance: 0.000000
  datasets:
    20251204-0104gtfsesg2026:
      path: datasets/20251204-0104_gtfs_esg_2026.zip
      default_bikes_allowed: false
      default_cars_allowed: false
      extend_calendar: false
      script: scripts/colors.lua
    20251211-0018gtfsflexooevv2026:
      path: datasets/20251211-0018_gtfs_flex_ooevv_2026.zip
      default_bikes_allowed: false
      default_cars_allowed: false
      extend_calendar: false
      script: scripts/colors.lua
    20251211-0018gtfsooevv2026:
      path: datasets/20251211-0018_gtfs_ooevv_2026.zip
      default_bikes_allowed: false
      default_cars_allowed: false
      extend_calendar: false
      script: scripts/colors.lua
    20251212-0226gtfsevu2026:
      path: datasets/20251212-0226_gtfs_evu_2026.zip
      default_bikes_allowed: false
      default_cars_allowed: false
      extend_calendar: false
      script: scripts/colors.lua
    20251212-0352gtfsflexsalzburgverkehr2026:
      path: datasets/20251212-0352_gtfs_flex_salzburgverkehr_2026.zip
      default_bikes_allowed: false
      default_cars_allowed: false
      extend_calendar: false
      script: scripts/colors.lua
    20251213-0015gtfsflexkaerntnerlinien2026:
      path: datasets/20251213-0015_gtfs_flex_kaerntnerlinien_2026.zip
      default_bikes_allowed: false
      default_cars_allowed: false
      extend_calendar: false
      script: scripts/colors.lua
    20251213-0216gtfsflexvor2026:
      path: datasets/20251213-0216_gtfs_flex_vor_2026.zip
      default_bikes_allowed: false
      default_cars_allowed: false
      extend_calendar: false
      script: scripts/colors.lua
    20251213-0241gtfsvvt2026:
      path: datasets/20251213-0241_gtfs_vvt_2026.zip
      default_bikes_allowed: false
      default_cars_allowed: false
      extend_calendar: false
      script: scripts/colors.lua
    20251213-0252gtfsflexvmobil2026:
      path: datasets/20251213-0252_gtfs_flex_vmobil_2026.zip
      default_bikes_allowed: false
      default_cars_allowed: false
      extend_calendar: false
      script: scripts/colors.lua
    20251214-0044gtfsflexverbundlinie2026:
      path: datasets/20251214-0044_gtfs_flex_verbundlinie_2026.zip
      default_bikes_allowed: false
      default_cars_allowed: false
      extend_calendar: false
      script: scripts/colors.lua
    flixbus-gtfs-generic-eu:
      path: datasets/flixbus_gtfs_generic_eu.zip
      default_bikes_allowed: false
      default_cars_allowed: false
      extend_calendar: false
      script: scripts/eu-flixbus.lua

elevators: false
street_routing: true
osr_footpath: false
geocoding: true
reverse_geocoding: true
