[project]
name = "route_lw1_at"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "dateparser>=1.2.2",
    "flask>=3.1.2",
    "jinja2>=3.1.6",
    "osmium>=4.2.0",
    "protobuf>=6.33.2",
    "requests>=2.32.5",
]
